import mongoose from "mongoose"
import { createHmac, randomBytes } from "crypto";

const userSchema = new mongoose.Schema({
    role: {
        type: String,
        require: true,
        default: "User",
    },
    fullName: {
        type: String,
        require: true,
    },
    username: {
        type: String,
        require: true,
        unique: true,
    },
    email: {
        type: String,
        require: true,
        unique: true,
    },
    salt: {
        type: String,
    },
    password: {
        type: String,
        required: true,
    },
    profileImageURL: {
        type: String,
        default: '/uploads/default.png'
    },
    address: {
        type: String,
        require: true,
    },
    contactNo: {
        type: String,
        require: true,
        unique: true,
    },
    reports: [
        {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Reports",
        }
    ],
    votes: [
        {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Votes",
        }
    ],
    notifications: [
        {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Notifications",
        }
    ]

}, { timestamps: true });


userSchema.pre("save", function (next) {
    const user = this;

    if (!user.isModified("password")) {
        return next();
    }

    const salt = randomBytes(16).toString("hex");
    const hashPassword = createHmac("sha256", salt)
        .update(user.password)
        .digest("hex");

    this.salt = salt;
    this.password = hashPassword;

    next();
});

userSchema.static("matchPassword", async function (email, password) {
    const user = await this.findOne({ email });
    if (!user) return false;

    const salt = user.salt;
    const hashPassword = user.password;

    // generate the password using the salt of the given user
    const userProvidedHash = createHmac("sha256", salt)
        .update(password)
        .digest("hex");

    //we now match the password in the database with the password generated by the user's salt
    if (hashPassword != userProvidedHash) return null;

    return { ...user._doc, password: undefined, salt: undefined };
});
const userModel = mongoose.model("User", userSchema);

export default userModel;